insert into medicine (id, name, price, description) values (1, 'Artalgia', 34, 'Pedal cycle passenger injured in collision with pedestrian or animal in nontraffic accident, sequela');
insert into medicine (id, name, price, description) values (2, 'GLYBURIDE AND METFORMIN HYDROCHLORIDE', 30, 'Nondisplaced fracture of head of left radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into medicine (id, name, price, description) values (3, 'Depacon', 74, 'Other extraarticular fracture of lower end of right radius, initial encounter for open fracture type I or II');
insert into medicine (id, name, price, description) values (4, 'Comfort Pac with Tizanidine', 22, 'Posterior subluxation of proximal end of tibia, left knee, initial encounter');
insert into medicine (id, name, price, description) values (5, 'Methocarbamol', 30, 'Occupant of animal-drawn vehicle injured in collision with railway train or railway vehicle, sequela');
insert into medicine (id, name, price, description) values (6, 'Sulfamethoxazole and Trimethoprim', 34, 'Pre-existing secondary hypertension complicating pregnancy');
insert into medicine (id, name, price, description) values (7, 'First Aid Shot Therapy Upset Stomach Relief', 46, 'Displaced fracture of distal phalanx of right index finger, subsequent encounter for fracture with malunion');
insert into medicine (id, name, price, description) values (8, 'methylphenidate hydrochloride', 71, 'Broken internal left hip prosthesis, sequela');
insert into medicine (id, name, price, description) values (9, 'Ziprasidone Hydrochloride', 88, 'Nondisplaced unspecified condyle fracture of lower end of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion');
insert into medicine (id, name, price, description) values (10, 'Pullularia', 23, 'Unspecified sprain of left ring finger, subsequent encounter');
insert into medicine (id, name, price, description) values (11, 'Multi-Symptom Non-Aspirin Cold Nighttime', 63, 'Burn and corrosion of lower limb, except ankle and foot');
insert into medicine (id, name, price, description) values (12, 'Trazodone Hydrochloride', 20, 'Minor laceration of right vertebral artery');
insert into medicine (id, name, price, description) values (13, 'Gongjinhyang Seol Whitening Intensive', 59, 'Laceration of popliteal vein, left leg, subsequent encounter');
insert into medicine (id, name, price, description) values (14, 'Olanzapine and Fluoxetine', 52, 'Adverse effect of smallpox vaccines');
insert into medicine (id, name, price, description) values (15, 'Amoxicillin and Clavulanate Potassium', 29, 'Traumatic subdural hemorrhage with loss of consciousness of unspecified duration, subsequent encounter');
insert into medicine (id, name, price, description) values (16, 'Rocky Mountain Juniper', 42, 'Toxic effect of homologues of benzene, accidental (unintentional), sequela');
insert into medicine (id, name, price, description) values (17, 'Helium Oxygen mixture', 70, 'War operations involving other fires, conflagrations and hot substances, civilian');
insert into medicine (id, name, price, description) values (18, 'Haloperidol Decanoate', 36, 'Fracture of unspecified part of scapula, left shoulder, subsequent encounter for fracture with delayed healing');
insert into medicine (id, name, price, description) values (19, 'VALCHLOR', 35, 'Malignant neoplasm of larynx, unspecified');
insert into medicine (id, name, price, description) values (20, 'Diltiazem Hydrochloride', 72, 'Other specified injuries unspecified forearm, sequela');
insert into medicine (id, name, price, description) values (21, 'Pain and Fever', 59, 'Contact with special construction vehicle in stationary use');
insert into medicine (id, name, price, description) values (22, 'DIORSNOW UV Shield White Reveal Moisturizing UV Protection Pearly White SPF 50', 100, 'Other tear of unspecified meniscus, current injury, right knee');
insert into medicine (id, name, price, description) values (23, 'TEMOVATE', 55, 'Corrosion of unspecified degree of multiple sites of unspecified shoulder and upper limb, except wrist and hand, initial encounter');
insert into medicine (id, name, price, description) values (24, 'Naftin', 28, 'Nonscarring hair loss, unspecified');
insert into medicine (id, name, price, description) values (25, 'Amitriptyline Hydrochloride', 63, 'Contact with other hot metals, initial encounter');
insert into medicine (id, name, price, description) values (26, 'Nitropress', 80, 'Flail joint, left shoulder');
insert into medicine (id, name, price, description) values (27, 'WARFARIN SODIUM', 95, 'Unspecified injury of unspecified blood vessel at shoulder and upper arm level');
insert into medicine (id, name, price, description) values (28, 'Gemfibrozil', 56, 'Corrosion of unspecified degree of multiple sites of lower limb, except ankle and foot');
insert into medicine (id, name, price, description) values (29, 'Amazonian Colored Clay Foundation Broad Spectrum SPF 15 Sunscreen', 29, 'Myositis ossificans progressiva, left toe(s)');
insert into medicine (id, name, price, description) values (30, 'Thario Instant Hand Sanitizer', 95, 'Raised antibody titer');
insert into medicine (id, name, price, description) values (31, 'Lisinopril and Hydrochlorothiazide', 15, 'Unspecified adverse effect of drug or medicament');
insert into medicine (id, name, price, description) values (32, 'MYUNG HAN MI IN DO RECOVERY BB', 55, 'Toxic effect of contact with other jellyfish, accidental (unintentional), sequela');
insert into medicine (id, name, price, description) values (33, 'daytime pe nitetime', 97, 'Paralytic lagophthalmos');
insert into medicine (id, name, price, description) values (34, 'Omeprazole', 14, 'Unspecified injury of other blood vessels at hip and thigh level, left leg, initial encounter');
insert into medicine (id, name, price, description) values (35, 'DEMEROL', 96, 'Corrosion of first degree of right palm, sequela');
insert into medicine (id, name, price, description) values (36, 'METOPROLOL SUCCINATE', 32, 'Fibrous dysplasia (monostotic), hand');
insert into medicine (id, name, price, description) values (37, 'Mammaryplex', 5, 'Other specified spondylopathies, sacral and sacrococcygeal region');
insert into medicine (id, name, price, description) values (38, 'Bacitracin Zinc', 86, 'Poisoning by local astringents and local detergents, accidental (unintentional)');
insert into medicine (id, name, price, description) values (39, 'Lemon Verbena Waterless Hand Wash', 92, 'Displaced fracture of lateral condyle of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion');
insert into medicine (id, name, price, description) values (40, 'Nicardipine Hydrochloride', 17, 'Open bite, left foot, initial encounter');
insert into medicine (id, name, price, description) values (41, 'Carbinoxamine Maleate', 8, 'Other chondrocalcinosis, unspecified hip');
insert into medicine (id, name, price, description) values (42, 'Zolpidem Tartrate', 78, 'Terrorism involving chemical weapons, terrorist injured, subsequent encounter');
insert into medicine (id, name, price, description) values (43, 'Fiber Therapy Regular Flavor', 84, 'Secondary Merkel cell carcinoma');
insert into medicine (id, name, price, description) values (44, 'Cephalexin', 81, 'Calculus of lower urinary tract, unspecified');
insert into medicine (id, name, price, description) values (45, 'Bupropion Hydrochloride', 28, 'Hairy cell leukemia, in remission');
insert into medicine (id, name, price, description) values (46, 'Quinapril', 97, 'Congenital bronchiectasis');
insert into medicine (id, name, price, description) values (47, 'Allergy Relief', 93, 'Laceration of blood vessel of left little finger, subsequent encounter');
insert into medicine (id, name, price, description) values (48, 'Giorgio Armani Face Fabric Second Skin Nude Makeup Broad Spectrum SPF 12 Sunscreen', 61, 'Acute hematogenous osteomyelitis, tibia and fibula');
insert into medicine (id, name, price, description) values (49, 'Denavir', 64, 'Functional disorders of polymorphonuclear neutrophils');
insert into medicine (id, name, price, description) values (50, 'germstar Original unscented', 13, 'Toxic effect of coral snake venom, undetermined, subsequent encounter');
insert into medicine (id, name, price, description) values (51, 'CITALOPRAM HYDROBROMIDE', 60, 'Burn of first degree of multiple sites of unspecified lower limb, except ankle and foot, sequela');
insert into medicine (id, name, price, description) values (52, 'Mark 3', 31, 'Injury of left internal carotid artery, intracranial portion, not elsewhere classified without loss of consciousness, initial encounter');
insert into medicine (id, name, price, description) values (53, 'Metformin Hydrochloride', 38, 'Postprocedural hemorrhage of a respiratory system organ or structure following a respiratory system procedure');
insert into medicine (id, name, price, description) values (54, 'Carisoprodol', 80, 'Nondisplaced fracture of head of right radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into medicine (id, name, price, description) values (55, 'rizatriptan benzoate', 62, 'Unspecified fracture of head of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into medicine (id, name, price, description) values (56, 'quetiapine fumarate', 70, 'Nondisplaced lateral mass fracture of first cervical vertebra');
insert into medicine (id, name, price, description) values (57, 'Nizatidine', 29, 'Adverse effect of antimalarials and drugs acting on other blood protozoa, subsequent encounter');
insert into medicine (id, name, price, description) values (58, 'SHISEIDO UV PROTECTIVE COMPACT (REFILL)', 72, 'Crushing injury of right forearm, initial encounter');
insert into medicine (id, name, price, description) values (59, 'cilostazol', 59, 'Laceration without foreign body of left great toe with damage to nail, initial encounter');
insert into medicine (id, name, price, description) values (60, 'Olanzapine', 84, 'Post-traumatic stress disorder (PTSD)');
insert into medicine (id, name, price, description) values (61, 'Renaforce', 14, 'Person on outside of pick-up truck or van injured in collision with heavy transport vehicle or bus in nontraffic accident');
insert into medicine (id, name, price, description) values (62, 'Treatment Set TS348283', 97, 'Unspecified fracture of fourth metacarpal bone, left hand, subsequent encounter for fracture with nonunion');
insert into medicine (id, name, price, description) values (63, 'Meperidine Hydrochloride', 29, 'Other myositis, right thigh');
insert into medicine (id, name, price, description) values (64, 'Anti-Bacterial Hand', 73, 'Displaced fracture of navicular [scaphoid] of unspecified foot, subsequent encounter for fracture with routine healing');
insert into medicine (id, name, price, description) values (65, 'Metoclopramide', 63, 'Underdosing of other anti-common-cold drugs, sequela');
insert into medicine (id, name, price, description) values (66, 'smart sense nicotine', 66, 'Adverse effect of unspecified agents primarily acting on the respiratory system, sequela');
insert into medicine (id, name, price, description) values (67, 'Feather Mixture', 74, 'Unspecified car occupant injured in collision with two- or three-wheeled motor vehicle in traffic accident, subsequent encounter');
insert into medicine (id, name, price, description) values (68, 'Piroxicam', 77, 'Sarcoid arthropathy');
insert into medicine (id, name, price, description) values (69, 'JIANZE SURGICAL SCRUB BRUSH NAIL CLEANER', 60, 'Peripheral opacity of cornea');
insert into medicine (id, name, price, description) values (70, 'Morphine Sulfate', 35, 'Unspecified fracture of lower end of unspecified ulna, subsequent encounter for open fracture type I or II with malunion');
insert into medicine (id, name, price, description) values (71, 'PAMO Kill Natural', 85, 'Poisoning by ganglionic blocking drugs, intentional self-harm, initial encounter');
insert into medicine (id, name, price, description) values (72, 'Dr.eslee Skin Mild', 16, 'Laceration with foreign body, unspecified foot, initial encounter');
insert into medicine (id, name, price, description) values (73, 'Urtica Conchae', 41, 'Leakage of other specified internal prosthetic devices, implants and grafts, sequela');
insert into medicine (id, name, price, description) values (74, 'Amlodipine Besylate and Benazepril Hydrochloride', 21, 'Salter-Harris Type I physeal fracture of phalanx of unspecified toe, subsequent encounter for fracture with routine healing');
insert into medicine (id, name, price, description) values (75, 'Hyoscyamine Sulfate', 22, 'Paraplegia, complete');
insert into medicine (id, name, price, description) values (76, 'ASSURE Antiseptic Hand Wipes', 25, 'Age-related osteoporosis with current pathological fracture, unspecified shoulder, initial encounter for fracture');
insert into medicine (id, name, price, description) values (77, 'Meloxicam', 90, 'Unspecified viral hepatitis');
insert into medicine (id, name, price, description) values (78, 'Dexferrum', 39, 'Unspecified occupant of three-wheeled motor vehicle injured in collision with other and unspecified motor vehicles in nontraffic accident');
insert into medicine (id, name, price, description) values (79, 'Athomer baby', 79, 'Puncture wound with foreign body of unspecified toe(s) without damage to nail, subsequent encounter');
insert into medicine (id, name, price, description) values (80, 'ZOLPIDEM TARTRATE', 18, 'Mixed cellularity Hodgkin lymphoma, intrathoracic lymph nodes');
insert into medicine (id, name, price, description) values (81, 'NABUMETONE', 99, 'Unspecified traumatic displaced spondylolisthesis of fifth cervical vertebra, initial encounter for open fracture');
insert into medicine (id, name, price, description) values (82, 'Selenium', 68, 'Other injury of extensor muscle, fascia and tendon of left ring finger at forearm level, initial encounter');
insert into medicine (id, name, price, description) values (83, 'Mirtazapine', 20, 'Strain of intrinsic muscle, fascia and tendon of unspecified thumb at wrist and hand level, sequela');
insert into medicine (id, name, price, description) values (84, 'White Hickory', 14, 'Crushing injury of left ankle, subsequent encounter');
insert into medicine (id, name, price, description) values (85, 'Sulfamethoxazole and Trimethoprim', 14, 'Poisoning by antihyperlipidemic and antiarteriosclerotic drugs, accidental (unintentional), initial encounter');
insert into medicine (id, name, price, description) values (86, 'Pentoxifylline', 41, 'Displaced spiral fracture of shaft of radius, unspecified arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion');
insert into medicine (id, name, price, description) values (87, 'Medi Stem Collagen', 17, 'Alcohol related disorders');
insert into medicine (id, name, price, description) values (88, 'Neumega', 67, 'Segmental and somatic dysfunction of lower extremity');
insert into medicine (id, name, price, description) values (89, 'Childrens Ibuprofen', 50, 'Military operations involving fragments from weapons, civilian, subsequent encounter');
insert into medicine (id, name, price, description) values (90, 'Maybelline New York Baby Lips Quenched Moisturizing Lip Balm SPF 20 Sunscreen', 65, 'Flat anterior chamber hypotony of right eye');
insert into medicine (id, name, price, description) values (91, 'Nitrogen', 98, 'Macrocheilia');
insert into medicine (id, name, price, description) values (92, 'Antiseptic', 83, 'Partial traumatic amputation of left foot, level unspecified, sequela');
insert into medicine (id, name, price, description) values (93, 'Gallium', 33, 'Displaced fracture of olecranon process without intraarticular extension of left ulna, initial encounter for closed fracture');
insert into medicine (id, name, price, description) values (94, 'Bupropion hydrochloride', 47, 'Other specified noninflammatory disorders of cervix uteri');
insert into medicine (id, name, price, description) values (95, 'simvastatin', 64, 'Unspecified physeal fracture of unspecified calcaneus, subsequent encounter for fracture with delayed healing');
insert into medicine (id, name, price, description) values (96, 'Naproxen', 5, 'Person on outside of car injured in collision with pedestrian or animal in traffic accident, initial encounter');
insert into medicine (id, name, price, description) values (97, 'Diethylpropion HydrochlorideER', 55, 'Unspecified dislocation of left middle finger, initial encounter');
insert into medicine (id, name, price, description) values (98, 'leader pain reliever', 46, 'Unspecified occupant of three-wheeled motor vehicle injured in collision with other motor vehicles in traffic accident, initial encounter');
insert into medicine (id, name, price, description) values (99, 'Sertraline hydrochloride', 32, 'Low-tension glaucoma, unspecified eye, moderate stage');
insert into medicine (id, name, price, description) values (100, 'LES BEIGES', 88, 'Poisoning by tetracyclines, accidental (unintentional), initial encounter');
insert into medicine (id, name, price, description) values (101, 'Neomycin and Polymyxin B Sulfates and Dexamethasone', 19, 'Poisoning by other general anesthetics, assault');
insert into medicine (id, name, price, description) values (102, 'Sunright BodyBlock SPF15', 47, 'Active stage of trachoma');
insert into medicine (id, name, price, description) values (103, 'ASPERGILLUS FUMIGATUS', 49, 'Corrosion of unspecified degree of unspecified elbow, sequela');
insert into medicine (id, name, price, description) values (104, 'Pre-Scrub II', 51, 'Corrosion of unspecified degree of back of left hand, subsequent encounter');
insert into medicine (id, name, price, description) values (105, 'Metolazone', 46, 'Contusion of ureter');
insert into medicine (id, name, price, description) values (106, 'Peptic Relief', 78, 'Corrosion of unspecified degree of toe(s) (nail)');
insert into medicine (id, name, price, description) values (107, 'Tea', 62, 'Poisoning by vitamins, accidental (unintentional), sequela');
insert into medicine (id, name, price, description) values (108, 'Benztropine Mesylate', 27, 'Underdosing of thrombolytic drugs');
insert into medicine (id, name, price, description) values (109, 'Jantoven', 48, 'Burn of second degree of neck, initial encounter');
insert into medicine (id, name, price, description) values (110, 'KONSYL Daily Therapy Fiber', 78, 'Open bite of left ear');
insert into medicine (id, name, price, description) values (111, 'Pain Relieving MUSFLEX', 38, 'Displaced oblique fracture of shaft of right tibia, initial encounter for closed fracture');
insert into medicine (id, name, price, description) values (112, 'Olanzapine', 82, 'Other fracture of lower end of right tibia, initial encounter for closed fracture');
insert into medicine (id, name, price, description) values (113, 'Trazodone Hydrochloride', 73, 'Jumping or diving from boat striking water surface causing drowning and submersion, subsequent encounter');
insert into medicine (id, name, price, description) values (114, 'Lil Drug Store Cold Relief', 65, 'Subluxation and dislocation of C4/C5 cervical vertebrae');
insert into medicine (id, name, price, description) values (115, 'Amoxicillin and Clavulanate Potassium', 33, 'Laceration of popliteal vein');
insert into medicine (id, name, price, description) values (116, 'Multi-Symptom Cold and Cough Daytime Nighttime', 3, 'Anterior cord syndrome of cervical spinal cord');
insert into medicine (id, name, price, description) values (117, 'Desloratadine', 100, 'Displacement of internal fixation device of bone of right lower leg, subsequent encounter');
insert into medicine (id, name, price, description) values (118, 'Cold Relief Daytime Multi-Symptom', 77, 'Unspecified petrositis');
insert into medicine (id, name, price, description) values (119, 'Clorpres', 21, 'Spontaneous rupture of flexor tendons, unspecified upper arm');
insert into medicine (id, name, price, description) values (120, 'Aveeno Active Naturals Skin Relief Healing', 62, 'Puncture wound without foreign body of lip, initial encounter');
insert into medicine (id, name, price, description) values (121, 'Blowfish', 89, 'Exposure to other inanimate mechanical forces');
insert into medicine (id, name, price, description) values (122, 'Metformin Hydrochloride', 16, 'Dislocation of radiocarpal joint of unspecified wrist');
insert into medicine (id, name, price, description) values (123, 'Prazosin Hydrochloride', 83, 'Necrosis of amputation stump, right lower extremity');
insert into medicine (id, name, price, description) values (124, 'Fentanyl', 20, 'Injury of unspecified nerve at hip and thigh level, left leg, subsequent encounter');
insert into medicine (id, name, price, description) values (125, 'Heparin Sodium', 5, 'Nondisplaced fracture of proximal third of navicular [scaphoid] bone of left wrist, subsequent encounter for fracture with nonunion');
insert into medicine (id, name, price, description) values (126, 'Leucovorin', 88, 'Other fracture of shaft of left femur');
insert into medicine (id, name, price, description) values (127, 'Candicide 12X', 52, 'Herpesviral infection of perianal skin and rectum');
insert into medicine (id, name, price, description) values (128, 'Ceftriaxone Sodium', 77, 'Prosthetic and other implants, materials and accessory radiological devices associated with adverse incidents');
insert into medicine (id, name, price, description) values (129, 'VERAPAMIL HYDROCHLORIDE', 86, 'Nondisplaced fracture of body of scapula, right shoulder, sequela');
insert into medicine (id, name, price, description) values (130, 'Primer', 9, 'Dislocation of distal radioulnar joint of right wrist, initial encounter');
insert into medicine (id, name, price, description) values (131, 'IASO A5 Super Brightening Formula', 99, 'Torus fracture of upper end of unspecified radius, initial encounter for closed fracture');
insert into medicine (id, name, price, description) values (132, 'SALICYLIC ACID', 34, 'Unspecified fracture of unspecified metacarpal bone, initial encounter for open fracture');
insert into medicine (id, name, price, description) values (133, 'Ringers', 62, 'Unstable burst fracture of T9-T10 vertebra, subsequent encounter for fracture with nonunion');
insert into medicine (id, name, price, description) values (134, 'Sodium Chloride', 33, 'Idiopathic progressive neuropathy');
insert into medicine (id, name, price, description) values (135, 'Sulphur', 30, 'Other cyst of bone, ankle and foot');
insert into medicine (id, name, price, description) values (136, 'Bambusa Aesculus', 95, 'Myogenic ptosis of eyelid');
insert into medicine (id, name, price, description) values (137, 'Iman Time Control All Day Moisture Complex SPF 15', 36, 'Snowboard accident');
insert into medicine (id, name, price, description) values (138, 'Timolol Maleate', 44, 'Thromboangiitis obliterans [Buerger''s disease]');
insert into medicine (id, name, price, description) values (139, 'Renagel', 63, 'Thoracoabdominal aortic ectasia');
insert into medicine (id, name, price, description) values (140, 'Guaifenesin', 31, 'Laceration of other muscles, fascia and tendons at shoulder and upper arm level, unspecified arm');
insert into medicine (id, name, price, description) values (141, 'dayrelief pe', 30, 'Dislocation of left scapula, subsequent encounter');
insert into medicine (id, name, price, description) values (142, 'LISINOPRIL AND HYDROCHLOROTHIAZIDE', 11, 'Other traumatic nondisplaced spondylolisthesis of third cervical vertebra, initial encounter for open fracture');
insert into medicine (id, name, price, description) values (143, 'North Burn Relief', 64, 'Displaced longitudinal fracture of right patella');
insert into medicine (id, name, price, description) values (144, 'Ferrum phosphoricum 6', 91, 'Pedal cycle passenger injured in collision with other pedal cycle in nontraffic accident');
insert into medicine (id, name, price, description) values (145, 'Diaper Rash', 66, 'Laceration with foreign body of unspecified great toe with damage to nail, subsequent encounter');
insert into medicine (id, name, price, description) values (146, 'IQUIX', 36, 'Passenger on bus injured in collision with heavy transport vehicle or bus in nontraffic accident, subsequent encounter');
insert into medicine (id, name, price, description) values (147, 'Shopko Antibacterial Foaming Hand Cleanser', 55, 'Sprain of metatarsophalangeal joint of right lesser toe(s), sequela');
insert into medicine (id, name, price, description) values (148, 'Livalo', 1, 'Blister (nonthermal) of breast, right breast, initial encounter');
insert into medicine (id, name, price, description) values (149, 'Hydrochlorothiazide', 61, 'Minor laceration of unspecified internal jugular vein, subsequent encounter');
insert into medicine (id, name, price, description) values (150, 'Lisinopril', 59, 'Placentitis, unspecified trimester, fetus 1');
insert into medicine (id, name, price, description) values (151, 'Senna-Lax', 43, 'Salter-Harris Type IV physeal fracture of lower end of left tibia');
insert into medicine (id, name, price, description) values (152, 'retaine PM', 9, 'Other disorders of peripheral nervous system');
insert into medicine (id, name, price, description) values (153, 'Bodycology', 35, 'Poisoning by other antidepressants, assault, subsequent encounter');
insert into medicine (id, name, price, description) values (154, 'Mycophenolate Mofetil', 97, 'Displaced segmental fracture of shaft of right tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into medicine (id, name, price, description) values (155, 'Hydrocodone Bitartrate and Acetaminophen', 70, 'Other fall from one level to another, sequela');
insert into medicine (id, name, price, description) values (156, 'ASPERGILLUS FUMIGATUS', 67, 'Assault by crashing of aircraft, sequela');
insert into medicine (id, name, price, description) values (157, 'Night Time Original', 23, 'Unspecified injury of unspecified innominate or subclavian vein, initial encounter');
insert into medicine (id, name, price, description) values (158, 'Irbesartan', 26, 'Toxic effect of zinc and its compounds, intentional self-harm');
insert into medicine (id, name, price, description) values (159, 'HYPERICUM PERFORATUM', 79, 'Salter-Harris Type I physeal fracture of lower end of unspecified tibia, subsequent encounter for fracture with nonunion');
insert into medicine (id, name, price, description) values (160, 'Kiehls Since 1851 Ultra Facial Moisturizer Broad Spectrum SPF 30 Sunscreen For All Skin Types', 43, 'Helicopter accident injuring occupant');
insert into medicine (id, name, price, description) values (161, 'Griseofulvin', 98, 'Recurrent pterygium of unspecified eye');
insert into medicine (id, name, price, description) values (162, 'Cerebromax', 80, 'Unspecified injury of other blood vessels of thorax, right side, initial encounter');
insert into medicine (id, name, price, description) values (163, 'Isoniazid', 15, 'Malignant neoplasm of ill-defined sites within the digestive system');
insert into medicine (id, name, price, description) values (164, 'Loperamide Hydrochloride', 73, 'Fournier gangrene');
insert into medicine (id, name, price, description) values (165, 'Lorazepam', 3, 'Laceration without foreign body of right front wall of thorax without penetration into thoracic cavity');
insert into medicine (id, name, price, description) values (166, 'Lemon Verbena Hand Sanitizer', 1, 'Nondisplaced segmental fracture of shaft of right fibula, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into medicine (id, name, price, description) values (167, 'Quack Grass', 23, 'Strongyloidiasis, unspecified');
insert into medicine (id, name, price, description) values (168, 'Cephalexin', 15, 'Ulnohumeral (joint) sprain of right elbow, subsequent encounter');
insert into medicine (id, name, price, description) values (169, 'NightTime Sinus Relief', 61, 'Other osteoporosis with current pathological fracture, unspecified lower leg, sequela');
insert into medicine (id, name, price, description) values (170, 'Usana Active Calcium', 44, 'Explosion of bicycle tire');
insert into medicine (id, name, price, description) values (171, 'Loud Child', 38, 'Puncture wound without foreign body of right upper arm, subsequent encounter');
insert into medicine (id, name, price, description) values (172, 'Clarins Super Restorative Day', 11, 'Chronic laryngitis');
insert into medicine (id, name, price, description) values (173, 'Bupivacaine HCl', 93, 'Complete traumatic metacarpophalangeal amputation of unspecified thumb, sequela');
insert into medicine (id, name, price, description) values (174, 'EROS CLASSIC SILICONE BODYGLIDE', 73, 'Poisoning by antifungal antibiotics, systemically used, intentional self-harm, sequela');
insert into medicine (id, name, price, description) values (175, 'Tamsulosin Hydrochloride', 97, 'Salter-Harris Type II physeal fracture of lower end of left tibia, sequela');
insert into medicine (id, name, price, description) values (176, 'Candicide 12X', 35, 'Subluxation and dislocation of unspecified interphalangeal joint of thumb');
insert into medicine (id, name, price, description) values (177, 'Medline Alcohol Prep', 64, 'Unstable burst fracture of third lumbar vertebra, subsequent encounter for fracture with delayed healing');
insert into medicine (id, name, price, description) values (178, 'WhiteWater Advanced Brightening', 70, 'Type III occipital condyle fracture, right side, initial encounter for closed fracture');
insert into medicine (id, name, price, description) values (179, 'SUPER SERUM', 99, 'Toxic effect of venom of other arthropod, intentional self-harm, sequela');
insert into medicine (id, name, price, description) values (180, 'Cyclo/Mag 10mg/200mg', 20, 'Salter-Harris Type II physeal fracture of upper end of radius, left arm, initial encounter for closed fracture');
insert into medicine (id, name, price, description) values (181, 'members mark famotidine', 35, 'Displaced fracture of unspecified radial styloid process, subsequent encounter for closed fracture with malunion');
insert into medicine (id, name, price, description) values (182, 'C-Nate DHA', 88, 'Unspecified injury of ulnar artery at forearm level, unspecified arm, initial encounter');
insert into medicine (id, name, price, description) values (183, 'DOLOR-PARCHE', 98, 'Maternal care for (suspected) damage to fetus from viral disease in mother, other fetus');
insert into medicine (id, name, price, description) values (184, 'Levofloxacin', 74, 'Military operations involving fragments from weapons, civilian, sequela');
insert into medicine (id, name, price, description) values (185, 'Clonazepam', 38, 'Acute promyelocytic leukemia, in remission');
insert into medicine (id, name, price, description) values (186, 'Montelukast Sodium', 39, 'Corrosion of third degree of left thigh');
insert into medicine (id, name, price, description) values (187, 'Nivea A Kiss of Recovery Medicated Lip Care', 74, 'Acquired absence of unspecified wrist');
insert into medicine (id, name, price, description) values (188, 'COMPLERA', 28, 'Insect bite (nonvenomous) of right thumb');
insert into medicine (id, name, price, description) values (189, 'Ciprofloxacin', 34, 'Other injury of muscle and tendon of long flexor muscle of toe at ankle and foot level');
insert into medicine (id, name, price, description) values (190, 'White Hickory', 80, 'Adult osteochondrosis of spine, lumbar region');
insert into medicine (id, name, price, description) values (191, 'Sumatriptan succinate', 18, 'Maternal care for hydrops fetalis, first trimester, fetus 2');
insert into medicine (id, name, price, description) values (192, 'Potassium Chloride in Lactated Ringers and Dextrose', 31, 'Erectile dysfunction following radiation therapy');
insert into medicine (id, name, price, description) values (193, 'Simply b, MD', 57, 'Disorders of muscle in diseases classified elsewhere, upper arm');
insert into medicine (id, name, price, description) values (194, 'Plus White Xtra Whitening', 71, 'Vestibular neuronitis, bilateral');
insert into medicine (id, name, price, description) values (195, 'Acyclovir', 26, 'Unspecified fracture of left pubis, subsequent encounter for fracture with routine healing');
insert into medicine (id, name, price, description) values (196, 'Mens Kirkland', 12, 'Puncture wound without foreign body of pharynx and cervical esophagus, initial encounter');
insert into medicine (id, name, price, description) values (197, 'Fentanyl', 76, 'Sprain of deltoid ligament of left ankle');
insert into medicine (id, name, price, description) values (198, 'Echinacea Thuja Special Order', 54, 'Nondisplaced fracture of shaft of other metacarpal bone, initial encounter for closed fracture');
insert into medicine (id, name, price, description) values (199, 'Sodium Chloride', 43, 'Corrosion of unspecified degree of right ankle, initial encounter');
insert into medicine (id, name, price, description) values (200, 'FUROSEMIDE', 94, 'Synovial hypertrophy, not elsewhere classified, left hand');
