insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (1, 1, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 56, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (2, 2, 'In hac habitasse platea dictumst.', 51, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (3, 3, 'Vestibulum sed magna at nunc commodo placerat.', 46, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (4, 4, 'Vestibulum sed magna at nunc commodo placerat.', 58, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (5, 5, 'Etiam justo.', 45, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (6, 6, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 14, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (7, 7, 'Quisque id justo sit amet sapien dignissim vestibulum.', 57, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (8, 8, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 31, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (9, 9, 'Morbi non lectus.', 3, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (10, 10, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 5, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (11, 11, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 33, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (12, 12, 'Pellentesque at nulla.', 33, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (13, 13, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 25, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (14, 14, 'Nunc purus.', 30, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (15, 15, 'Duis at velit eu est congue elementum.', 54, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (16, 16, 'Maecenas ut massa quis augue luctus tincidunt.', 46, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (17, 17, 'Aliquam erat volutpat.', 11, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (18, 18, 'Vestibulum rutrum rutrum neque.', 4, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (19, 19, 'Proin eu mi.', 3, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (20, 20, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 59, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (21, 21, 'Maecenas pulvinar lobortis est.', 42, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (22, 22, 'Integer ac leo.', 49, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (23, 23, 'Nunc nisl.', 14, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (24, 24, 'In hac habitasse platea dictumst.', 60, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (25, 25, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 32, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (26, 26, 'Nulla facilisi.', 5, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (27, 27, 'Phasellus sit amet erat.', 37, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (28, 28, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 55, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (29, 29, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 12, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (30, 30, 'Sed vel enim sit amet nunc viverra dapibus.', 17, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (31, 31, 'Praesent lectus.', 40, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (32, 32, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 57, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (33, 33, 'Duis bibendum.', 24, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (34, 34, 'Etiam vel augue.', 31, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (35, 35, 'Nam tristique tortor eu pede.', 11, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (36, 36, 'Nulla tempus.', 20, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (37, 37, 'Pellentesque viverra pede ac diam.', 19, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (38, 38, 'Mauris ullamcorper purus sit amet nulla.', 46, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (39, 39, 'Etiam vel augue.', 8, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (40, 40, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 60, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (41, 41, 'Morbi non lectus.', 7, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (42, 42, 'Donec dapibus.', 11, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (43, 43, 'Sed vel enim sit amet nunc viverra dapibus.', 45, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (44, 44, 'In quis justo.', 46, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (45, 45, 'Nulla mollis molestie lorem.', 29, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (46, 46, 'Aliquam sit amet diam in magna bibendum imperdiet.', 27, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (47, 47, 'Donec semper sapien a libero.', 6, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (48, 48, 'In hac habitasse platea dictumst.', 43, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (49, 49, 'Nulla ac enim.', 15, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (50, 50, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 22, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (51, 51, 'Praesent lectus.', 43, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (52, 52, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 28, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (53, 53, 'Etiam justo.', 4, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (54, 54, 'In eleifend quam a odio.', 23, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (55, 55, 'In hac habitasse platea dictumst.', 17, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (56, 56, 'Proin interdum mauris non ligula pellentesque ultrices.', 60, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (57, 57, 'Aenean fermentum.', 32, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (58, 58, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 6, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (59, 59, 'Integer a nibh.', 49, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (60, 60, 'Maecenas tincidunt lacus at velit.', 15, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (61, 61, 'Vivamus vel nulla eget eros elementum pellentesque.', 18, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (62, 62, 'Aliquam non mauris.', 42, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (63, 63, 'Nunc rhoncus dui vel sem.', 15, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (64, 64, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 43, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (65, 65, 'Mauris ullamcorper purus sit amet nulla.', 12, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (66, 66, 'Mauris sit amet eros.', 32, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (67, 67, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 52, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (68, 68, 'Sed accumsan felis.', 2, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (69, 69, 'Aenean lectus.', 3, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (70, 70, 'Suspendisse ornare consequat lectus.', 5, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (71, 71, 'Suspendisse potenti.', 24, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (72, 72, 'Nulla tellus.', 11, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (73, 73, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 8, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (74, 74, 'Aenean auctor gravida sem.', 51, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (75, 75, 'Duis mattis egestas metus.', 49, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (76, 76, 'Pellentesque viverra pede ac diam.', 54, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (77, 77, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 22, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (78, 78, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 6, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (79, 79, 'Aliquam erat volutpat.', 23, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (80, 80, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 19, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (81, 81, 'Vivamus in felis eu sapien cursus vestibulum.', 34, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (82, 82, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 6, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (83, 83, 'Aliquam sit amet diam in magna bibendum imperdiet.', 5, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (84, 84, 'Sed ante.', 11, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (85, 85, 'Aliquam erat volutpat.', 21, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (86, 86, 'Vivamus in felis eu sapien cursus vestibulum.', 58, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (87, 87, 'Sed ante.', 39, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (88, 88, 'Sed sagittis.', 54, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (89, 89, 'In hac habitasse platea dictumst.', 35, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (90, 90, 'Donec quis orci eget orci vehicula condimentum.', 19, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (91, 91, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 59, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (92, 92, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 51, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (93, 93, 'Integer tincidunt ante vel ipsum.', 10, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (94, 94, 'Nullam varius.', 43, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (95, 95, 'Maecenas ut massa quis augue luctus tincidunt.', 38, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (96, 96, 'Donec semper sapien a libero.', 20, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (97, 97, 'Nulla justo.', 54, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (98, 98, 'Aenean fermentum.', 35, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (99, 99, 'Maecenas rhoncus aliquam lacus.', 13, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (100, 100, 'Praesent blandit lacinia erat.', 4, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (101, 101, 'Maecenas tincidunt lacus at velit.', 60, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (102, 102, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 20, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (103, 103, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 39, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (104, 104, 'Donec posuere metus vitae ipsum.', 33, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (105, 105, 'Ut at dolor quis odio consequat varius.', 40, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (106, 106, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 51, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (107, 107, 'Integer non velit.', 26, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (108, 108, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 19, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (109, 109, 'Aliquam non mauris.', 30, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (110, 110, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 43, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (111, 111, 'Etiam vel augue.', 47, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (112, 112, 'Pellentesque ultrices mattis odio.', 33, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (113, 113, 'Aliquam non mauris.', 44, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (114, 114, 'Suspendisse ornare consequat lectus.', 31, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (115, 115, 'Nulla tellus.', 28, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (116, 116, 'Praesent lectus.', 46, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (117, 117, 'Suspendisse ornare consequat lectus.', 40, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (118, 118, 'In hac habitasse platea dictumst.', 54, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (119, 119, 'Aenean sit amet justo.', 24, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (120, 120, 'Etiam vel augue.', 31, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (121, 121, 'Integer a nibh.', 4, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (122, 122, 'Maecenas ut massa quis augue luctus tincidunt.', 47, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (123, 123, 'Aenean lectus.', 53, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (124, 124, 'Etiam vel augue.', 19, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (125, 125, 'Aenean lectus.', 24, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (126, 126, 'Duis aliquam convallis nunc.', 60, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (127, 127, 'Nulla mollis molestie lorem.', 34, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (128, 128, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 23, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (129, 129, 'Cras non velit nec nisi vulputate nonummy.', 3, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (130, 130, 'Nulla ut erat id mauris vulputate elementum.', 26, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (131, 131, 'Etiam justo.', 16, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (132, 132, 'Donec vitae nisi.', 19, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (133, 133, 'Quisque ut erat.', 42, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (134, 134, 'Cras non velit nec nisi vulputate nonummy.', 24, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (135, 135, 'Donec ut mauris eget massa tempor convallis.', 59, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (136, 136, 'Nam tristique tortor eu pede.', 8, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (137, 137, 'Vestibulum rutrum rutrum neque.', 36, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (138, 138, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 27, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (139, 139, 'Curabitur gravida nisi at nibh.', 60, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (140, 140, 'Vivamus vel nulla eget eros elementum pellentesque.', 7, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (141, 141, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 29, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (142, 142, 'Curabitur convallis.', 39, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (143, 143, 'Curabitur convallis.', 30, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (144, 144, 'Nunc rhoncus dui vel sem.', 45, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (145, 145, 'Fusce consequat.', 29, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (146, 146, 'Donec ut mauris eget massa tempor convallis.', 56, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (147, 147, 'In sagittis dui vel nisl.', 38, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (148, 148, 'Morbi ut odio.', 3, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (149, 149, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 22, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (150, 150, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 21, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (151, 151, 'Pellentesque at nulla.', 36, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (152, 152, 'Aliquam sit amet diam in magna bibendum imperdiet.', 42, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (153, 153, 'Vestibulum ac est lacinia nisi venenatis tristique.', 19, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (154, 154, 'Duis consequat dui nec nisi volutpat eleifend.', 41, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (155, 155, 'Curabitur at ipsum ac tellus semper interdum.', 45, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (156, 156, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 29, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (157, 157, 'Suspendisse potenti.', 57, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (158, 158, 'Nulla ut erat id mauris vulputate elementum.', 3, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (159, 159, 'Proin at turpis a pede posuere nonummy.', 17, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (160, 160, 'In hac habitasse platea dictumst.', 12, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (161, 161, 'Vestibulum sed magna at nunc commodo placerat.', 49, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (162, 162, 'Integer ac leo.', 7, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (163, 163, 'Duis ac nibh.', 3, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (164, 164, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 37, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (165, 165, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 48, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (166, 166, 'Donec semper sapien a libero.', 32, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (167, 167, 'Curabitur convallis.', 32, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (168, 168, 'Nulla justo.', 56, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (169, 169, 'Maecenas tincidunt lacus at velit.', 14, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (170, 170, 'Donec posuere metus vitae ipsum.', 4, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (171, 171, 'Praesent id massa id nisl venenatis lacinia.', 11, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (172, 172, 'Nulla tellus.', 35, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (173, 173, 'Praesent lectus.', 12, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (174, 174, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 35, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (175, 175, 'Mauris sit amet eros.', 48, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (176, 176, 'Donec posuere metus vitae ipsum.', 23, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (177, 177, 'Pellentesque at nulla.', 10, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (178, 178, 'Mauris ullamcorper purus sit amet nulla.', 13, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (179, 179, 'Curabitur in libero ut massa volutpat convallis.', 27, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (180, 180, 'Integer ac neque.', 1, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (181, 181, 'Donec dapibus.', 18, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (182, 182, 'Integer tincidunt ante vel ipsum.', 53, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (183, 183, 'Aliquam quis turpis eget elit sodales scelerisque.', 54, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (184, 184, 'Donec dapibus.', 1, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (185, 185, 'In congue.', 25, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (186, 186, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 29, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (187, 187, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 41, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (188, 188, 'Maecenas tincidunt lacus at velit.', 38, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (189, 189, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 39, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (190, 190, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 27, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (191, 191, 'Mauris lacinia sapien quis libero.', 49, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (192, 192, 'Suspendisse potenti.', 25, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (193, 193, 'In congue.', 24, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (194, 194, 'Suspendisse potenti.', 51, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (195, 195, 'Morbi ut odio.', 20, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (196, 196, 'Morbi non lectus.', 58, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (197, 197, 'In sagittis dui vel nisl.', 23, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (198, 198, 'Cras pellentesque volutpat dui.', 39, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (199, 199, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 48, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (200, 200, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 8, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (201, 201, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 49, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (202, 202, 'Quisque id justo sit amet sapien dignissim vestibulum.', 16, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (203, 203, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 55, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (204, 204, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 23, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (205, 205, 'Curabitur at ipsum ac tellus semper interdum.', 51, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (206, 206, 'Morbi non lectus.', 28, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (207, 207, 'In hac habitasse platea dictumst.', 41, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (208, 208, 'Suspendisse ornare consequat lectus.', 4, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (209, 209, 'Ut at dolor quis odio consequat varius.', 31, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (210, 210, 'Etiam justo.', 45, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (211, 211, 'Nullam molestie nibh in lectus.', 21, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (212, 212, 'Vivamus in felis eu sapien cursus vestibulum.', 60, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (213, 213, 'Curabitur gravida nisi at nibh.', 15, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (214, 214, 'Mauris sit amet eros.', 41, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (215, 215, 'Cras non velit nec nisi vulputate nonummy.', 4, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (216, 216, 'Fusce posuere felis sed lacus.', 13, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (217, 217, 'Duis at velit eu est congue elementum.', 8, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (218, 218, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 23, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (219, 219, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 47, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (220, 220, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 11, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (221, 221, 'Nunc nisl.', 20, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (222, 222, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 13, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (223, 223, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 58, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (224, 224, 'Aenean lectus.', 21, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (225, 225, 'Vivamus vel nulla eget eros elementum pellentesque.', 46, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (226, 226, 'Nulla tellus.', 47, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (227, 227, 'Vivamus vel nulla eget eros elementum pellentesque.', 1, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (228, 228, 'Phasellus in felis.', 8, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (229, 229, 'Nulla ac enim.', 26, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (230, 230, 'Fusce consequat.', 43, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (231, 231, 'Fusce consequat.', 36, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (232, 232, 'Proin risus.', 3, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (233, 233, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 39, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (234, 234, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 16, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (235, 235, 'Aliquam erat volutpat.', 53, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (236, 236, 'Ut at dolor quis odio consequat varius.', 22, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (237, 237, 'Pellentesque eget nunc.', 36, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (238, 238, 'Proin eu mi.', 31, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (239, 239, 'Praesent blandit lacinia erat.', 8, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (240, 240, 'Morbi vel lectus in quam fringilla rhoncus.', 51, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (241, 241, 'Donec posuere metus vitae ipsum.', 2, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (242, 242, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 29, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (243, 243, 'Phasellus in felis.', 43, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (244, 244, 'Duis at velit eu est congue elementum.', 37, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (245, 245, 'Donec dapibus.', 10, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (246, 246, 'In congue.', 29, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (247, 247, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 54, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (248, 248, 'Maecenas tincidunt lacus at velit.', 31, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (249, 249, 'Donec dapibus.', 7, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (250, 250, 'Mauris ullamcorper purus sit amet nulla.', 5, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (251, 251, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 15, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (252, 252, 'Duis at velit eu est congue elementum.', 27, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (253, 253, 'Pellentesque at nulla.', 45, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (254, 254, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 15, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (255, 255, 'Morbi vel lectus in quam fringilla rhoncus.', 46, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (256, 256, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 17, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (257, 257, 'Vestibulum rutrum rutrum neque.', 58, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (258, 258, 'Donec quis orci eget orci vehicula condimentum.', 47, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (259, 259, 'Duis ac nibh.', 21, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (260, 260, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 31, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (261, 261, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 48, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (262, 262, 'Quisque ut erat.', 16, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (263, 263, 'In blandit ultrices enim.', 13, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (264, 264, 'Donec ut mauris eget massa tempor convallis.', 37, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (265, 265, 'Ut at dolor quis odio consequat varius.', 16, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (266, 266, 'Quisque porta volutpat erat.', 56, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (267, 267, 'Morbi non quam nec dui luctus rutrum.', 58, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (268, 268, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 35, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (269, 269, 'Integer ac leo.', 14, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (270, 270, 'Donec posuere metus vitae ipsum.', 16, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (271, 271, 'Suspendisse potenti.', 39, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (272, 272, 'In hac habitasse platea dictumst.', 32, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (273, 273, 'Etiam vel augue.', 48, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (274, 274, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 51, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (275, 275, 'Donec ut mauris eget massa tempor convallis.', 50, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (276, 276, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 37, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (277, 277, 'Morbi ut odio.', 10, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (278, 278, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 11, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (279, 279, 'Suspendisse potenti.', 14, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (280, 280, 'Integer ac leo.', 38, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (281, 281, 'Pellentesque ultrices mattis odio.', 34, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (282, 282, 'Integer tincidunt ante vel ipsum.', 52, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (283, 283, 'Nullam molestie nibh in lectus.', 20, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (284, 284, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 22, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (285, 285, 'Morbi quis tortor id nulla ultrices aliquet.', 23, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (286, 286, 'Donec vitae nisi.', 3, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (287, 287, 'Mauris ullamcorper purus sit amet nulla.', 6, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (288, 288, 'Curabitur in libero ut massa volutpat convallis.', 21, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (289, 289, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 48, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (290, 290, 'Nulla ut erat id mauris vulputate elementum.', 30, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (291, 291, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 47, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (292, 292, 'Pellentesque viverra pede ac diam.', 8, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (293, 293, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 50, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (294, 294, 'Morbi vel lectus in quam fringilla rhoncus.', 16, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (295, 295, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 44, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (296, 296, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 49, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (297, 297, 'Etiam vel augue.', 3, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (298, 298, 'Pellentesque eget nunc.', 1, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (299, 299, 'Duis aliquam convallis nunc.', 24, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (300, 300, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 50, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (301, 301, 'Phasellus in felis.', 30, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (302, 302, 'Maecenas tincidunt lacus at velit.', 8, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (303, 303, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 43, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (304, 304, 'Nam tristique tortor eu pede.', 32, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (305, 305, 'Nullam porttitor lacus at turpis.', 13, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (306, 306, 'Nulla suscipit ligula in lacus.', 23, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (307, 307, 'Integer non velit.', 20, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (308, 308, 'Pellentesque ultrices mattis odio.', 9, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (309, 309, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 8, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (310, 310, 'Integer ac leo.', 46, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (311, 311, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 8, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (312, 312, 'Mauris sit amet eros.', 20, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (313, 313, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 5, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (314, 314, 'Aenean auctor gravida sem.', 15, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (315, 315, 'Nulla facilisi.', 46, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (316, 316, 'Nullam molestie nibh in lectus.', 8, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (317, 317, 'Cras non velit nec nisi vulputate nonummy.', 33, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (318, 318, 'Proin at turpis a pede posuere nonummy.', 39, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (319, 319, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 41, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (320, 320, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 53, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (321, 321, 'Vestibulum ac est lacinia nisi venenatis tristique.', 20, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (322, 322, 'Duis at velit eu est congue elementum.', 11, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (323, 323, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 5, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (324, 324, 'Pellentesque at nulla.', 39, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (325, 325, 'Vivamus in felis eu sapien cursus vestibulum.', 30, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (326, 326, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 29, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (327, 327, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 32, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (328, 328, 'Praesent lectus.', 30, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (329, 329, 'Aenean sit amet justo.', 22, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (330, 330, 'Maecenas tincidunt lacus at velit.', 50, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (331, 331, 'Nullam molestie nibh in lectus.', 41, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (332, 332, 'Duis bibendum.', 3, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (333, 333, 'Morbi ut odio.', 35, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (334, 334, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 15, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (335, 335, 'Aliquam quis turpis eget elit sodales scelerisque.', 13, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (336, 336, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 10, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (337, 337, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 4, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (338, 338, 'Aliquam quis turpis eget elit sodales scelerisque.', 11, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (339, 339, 'In hac habitasse platea dictumst.', 10, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (340, 340, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 4, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (341, 341, 'Vestibulum ac est lacinia nisi venenatis tristique.', 49, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (342, 342, 'Duis consequat dui nec nisi volutpat eleifend.', 13, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (343, 343, 'Nulla tempus.', 27, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (344, 344, 'Ut tellus.', 59, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (345, 345, 'In quis justo.', 49, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (346, 346, 'Nulla facilisi.', 24, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (347, 347, 'In eleifend quam a odio.', 54, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (348, 348, 'Vivamus vel nulla eget eros elementum pellentesque.', 56, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (349, 349, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 16, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (350, 350, 'Nulla tellus.', 13, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (351, 351, 'Ut tellus.', 44, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (352, 352, 'Donec dapibus.', 43, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (353, 353, 'Curabitur convallis.', 6, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (354, 354, 'Integer ac neque.', 21, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (355, 355, 'Morbi a ipsum.', 23, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (356, 356, 'Duis at velit eu est congue elementum.', 59, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (357, 357, 'Etiam pretium iaculis justo.', 57, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (358, 358, 'Morbi quis tortor id nulla ultrices aliquet.', 39, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (359, 359, 'Duis mattis egestas metus.', 52, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (360, 360, 'Curabitur convallis.', 24, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (361, 361, 'Phasellus in felis.', 26, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (362, 362, 'Phasellus id sapien in sapien iaculis congue.', 15, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (363, 363, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 34, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (364, 364, 'Quisque porta volutpat erat.', 41, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (365, 365, 'Praesent blandit lacinia erat.', 56, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (366, 366, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 31, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (367, 367, 'Duis mattis egestas metus.', 4, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (368, 368, 'Maecenas rhoncus aliquam lacus.', 41, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (369, 369, 'Nulla tempus.', 47, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (370, 370, 'Nullam molestie nibh in lectus.', 21, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (371, 371, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 54, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (372, 372, 'Nam dui.', 34, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (373, 373, 'Mauris ullamcorper purus sit amet nulla.', 31, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (374, 374, 'Morbi a ipsum.', 12, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (375, 375, 'Ut at dolor quis odio consequat varius.', 36, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (376, 376, 'Nunc purus.', 12, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (377, 377, 'Maecenas rhoncus aliquam lacus.', 45, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (378, 378, 'In hac habitasse platea dictumst.', 60, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (379, 379, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 59, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (380, 380, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 51, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (381, 381, 'Maecenas tincidunt lacus at velit.', 46, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (382, 382, 'In blandit ultrices enim.', 29, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (383, 383, 'Pellentesque at nulla.', 48, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (384, 384, 'Sed ante.', 6, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (385, 385, 'Nunc purus.', 8, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (386, 386, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 27, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (387, 387, 'Aliquam non mauris.', 26, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (388, 388, 'Nulla facilisi.', 56, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (389, 389, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 2, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (390, 390, 'Duis at velit eu est congue elementum.', 47, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (391, 391, 'Integer non velit.', 39, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (392, 392, 'Nulla tempus.', 10, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (393, 393, 'Suspendisse ornare consequat lectus.', 18, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (394, 394, 'Aliquam quis turpis eget elit sodales scelerisque.', 20, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (395, 395, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 52, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (396, 396, 'Quisque id justo sit amet sapien dignissim vestibulum.', 58, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (397, 397, 'Phasellus in felis.', 18, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (398, 398, 'Suspendisse potenti.', 10, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (399, 399, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 17, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (400, 400, 'Praesent blandit.', 21, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (401, 401, 'Quisque id justo sit amet sapien dignissim vestibulum.', 54, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (402, 402, 'Maecenas ut massa quis augue luctus tincidunt.', 1, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (403, 403, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 59, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (404, 404, 'Quisque porta volutpat erat.', 52, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (405, 405, 'Vestibulum rutrum rutrum neque.', 25, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (406, 406, 'Aenean fermentum.', 3, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (407, 407, 'Sed accumsan felis.', 9, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (408, 408, 'Aliquam erat volutpat.', 47, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (409, 409, 'Phasellus id sapien in sapien iaculis congue.', 14, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (410, 410, 'Duis ac nibh.', 44, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (411, 411, 'Suspendisse accumsan tortor quis turpis.', 7, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (412, 412, 'Cras non velit nec nisi vulputate nonummy.', 3, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (413, 413, 'Integer non velit.', 54, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (414, 414, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 7, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (415, 415, 'Proin at turpis a pede posuere nonummy.', 24, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (416, 416, 'Suspendisse potenti.', 46, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (417, 417, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 22, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (418, 418, 'Sed sagittis.', 7, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (419, 419, 'Aliquam non mauris.', 36, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (420, 420, 'Curabitur at ipsum ac tellus semper interdum.', 43, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (421, 421, 'Sed ante.', 28, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (422, 422, 'Proin eu mi.', 15, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (423, 423, 'Nulla ac enim.', 46, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (424, 424, 'Nullam molestie nibh in lectus.', 37, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (425, 425, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 6, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (426, 426, 'Sed sagittis.', 39, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (427, 427, 'Praesent blandit.', 12, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (428, 428, 'Nullam porttitor lacus at turpis.', 56, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (429, 429, 'Vivamus in felis eu sapien cursus vestibulum.', 29, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (430, 430, 'Maecenas ut massa quis augue luctus tincidunt.', 21, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (431, 431, 'Etiam faucibus cursus urna.', 26, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (432, 432, 'Nullam porttitor lacus at turpis.', 17, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (433, 433, 'Vivamus in felis eu sapien cursus vestibulum.', 9, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (434, 434, 'Quisque id justo sit amet sapien dignissim vestibulum.', 36, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (435, 435, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 41, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (436, 436, 'Phasellus in felis.', 49, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (437, 437, 'Nulla suscipit ligula in lacus.', 41, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (438, 438, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 43, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (439, 439, 'Cras non velit nec nisi vulputate nonummy.', 16, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (440, 440, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 51, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (441, 441, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 48, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (442, 442, 'Donec quis orci eget orci vehicula condimentum.', 37, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (443, 443, 'In congue.', 25, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (444, 444, 'Sed accumsan felis.', 38, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (445, 445, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 12, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (446, 446, 'Integer non velit.', 6, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (447, 447, 'Integer ac neque.', 16, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (448, 448, 'Integer a nibh.', 32, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (449, 449, 'Maecenas ut massa quis augue luctus tincidunt.', 12, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (450, 450, 'Sed ante.', 53, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (451, 451, 'Donec ut mauris eget massa tempor convallis.', 31, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (452, 452, 'Sed vel enim sit amet nunc viverra dapibus.', 21, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (453, 453, 'Suspendisse potenti.', 19, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (454, 454, 'In congue.', 27, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (455, 455, 'Sed sagittis.', 5, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (456, 456, 'Nulla tempus.', 26, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (457, 457, 'Donec ut mauris eget massa tempor convallis.', 45, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (458, 458, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 6, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (459, 459, 'Donec semper sapien a libero.', 19, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (460, 460, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 39, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (461, 461, 'Donec ut dolor.', 24, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (462, 462, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 21, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (463, 463, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 25, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (464, 464, 'Etiam faucibus cursus urna.', 49, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (465, 465, 'In hac habitasse platea dictumst.', 1, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (466, 466, 'Mauris ullamcorper purus sit amet nulla.', 37, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (467, 467, 'Aenean auctor gravida sem.', 16, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (468, 468, 'Donec posuere metus vitae ipsum.', 27, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (469, 469, 'Proin risus.', 25, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (470, 470, 'Morbi vel lectus in quam fringilla rhoncus.', 5, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (471, 471, 'Cras pellentesque volutpat dui.', 55, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (472, 472, 'Proin at turpis a pede posuere nonummy.', 56, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (473, 473, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 2, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (474, 474, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 42, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (475, 475, 'Ut at dolor quis odio consequat varius.', 21, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (476, 476, 'Donec posuere metus vitae ipsum.', 56, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (477, 477, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 22, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (478, 478, 'Morbi quis tortor id nulla ultrices aliquet.', 33, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (479, 479, 'Suspendisse potenti.', 31, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (480, 480, 'Duis ac nibh.', 23, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (481, 481, 'Donec ut dolor.', 36, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (482, 482, 'Quisque ut erat.', 3, 100);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (483, 483, 'Aenean sit amet justo.', 50, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (484, 484, 'Aliquam quis turpis eget elit sodales scelerisque.', 39, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (485, 485, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 9, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (486, 486, 'Etiam pretium iaculis justo.', 6, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (487, 487, 'Nunc purus.', 45, 300);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (488, 488, 'Maecenas ut massa quis augue luctus tincidunt.', 2, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (489, 489, 'Quisque porta volutpat erat.', 23, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (490, 490, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 52, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (491, 491, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2, 250);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (492, 492, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 43, 500);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (493, 493, 'Suspendisse potenti.', 58, 350);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (494, 494, 'Pellentesque viverra pede ac diam.', 12, 200);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (495, 495, 'Duis mattis egestas metus.', 16, 450);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (496, 496, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 43, 400);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (497, 497, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 58, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (498, 498, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 39, 50);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (499, 499, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 10, 150);
insert into prescription (id, appointment_id, message, treatment_duration, consult_price) values (500, 500, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 57, 400);
